test_that("checker variant games work as expected", {
	skip_if_not_installed("ppcli")
	skip_on_os("windows")

	expect_snapshot(cat_piece(checker_american_checkers()))
	expect_snapshot(cat_piece(checker_american_pool_checkers()))
	expect_snapshot(cat_piece(checker_corner_checkers()))
	expect_snapshot(cat_piece(checker_dameo()))
	expect_snapshot(cat_piece(checker_international_checkers()))
	expect_snapshot(suppressWarnings(cat_piece(checker_italian_checkers())))
	expect_snapshot(cat_piece(checker_lasca()))
	expect_snapshot(cat_piece(checker_one_way_checkers()))
	expect_snapshot(cat_piece(checker_singaporean_checkers()))
	expect_snapshot(cat_piece(checker_thai_checkers()))
	expect_snapshot(cat_piece(checker_turkish_checkers()))
	expect_snapshot(cat_piece(checker_zimbabwean_pool_checkers()))
})
